# Homicide: A Year of Killing in Saint Lucia


> "You are entrusted with the pursuit of the most extraordinary of crimes: the theft of human life. You speak for the dead. You avenge those lost to the world" 
-- David Simon 

# Introduction

As most of Saint Lucia's citizens gathered to celebrate the passing of another year and welcome in the new, at roughly 8:00pm in the garage of a rented house two men lay dying marking the 59th and 60th murders of 2017. Unofficially, this would mark the deadliest year in recent history, surpassing the previous record of 52, a year which included a number of extra-judicial killings by police[^1].

Three months into 2018 and last year's record number of homicides has faded from the public debate as other issues have taken center stage in the media. What little discussion has taken place has often been without empirical basis and lacks the perspective and objectivity necessary to inform corrective public policy to help redress the alarming rate of violent crime, an issue that is not unique to Saint Lucia[^2], with Trinidad and Tobago[^3], and Jamaica[^4] reporting high levels of homicides. 

[[FIGURE 1: Homicides in Saint Lucia 2000 - 2017]]

TODO
- Profile of victims
- What motivated me to write this piece
- Why does this matter

# Body

- Finding 1
- Finding 2
- Finding 3


# Conclusions

- What have we learned
- Implications for public policy
- 


# Notes

## Data Collection

## Footnotes

[^1]: http://www.jamaicaobserver.com/news/Extrajudicial-killings-report--disturbing--hopeless-and-questionable---says-former-St-Lucia-PM

[^2]: https://www.insightcrime.org/news/analysis/caribbean-has-violence-problem-not-crime-problem-report/

[^3]: http://www.looptt.com/content/bloody-january-murder-count-60

[^4]: http://jamaica-gleaner.com/article/lead-stories/20180105/2017-murders-divisions-st-james-leads-335-homicides
