> "You are entrusted with the pursuit of the most extraordinary of crimes: the theft of human life. You speak for the dead. You avenge those lost to the world" 
-- David Simon 

# Introduction

As most of Saint Lucia's citizens gathered to celebrate the passing of another year and welcome in the new, at roughly 8:00pm in the garage of a rented house two men lay dying marking the 59th and 60th murders of 2017. Unofficially, this would mark the deadliest year in recent history, surpassing the previous record of 52, a year which included a number of extra-judicial killings by police[^1].

Four months into 2018 and last year's record number of homicides has faded from the public debate as other issues have taken center stage in the media. What little discussion has taken place has often been without empirical basis and lacks the perspective and objectivity necessary to inform corrective public policy to help redress the alarming rate of violent crime, an issue that is not unique to Saint Lucia[^2], with Trinidad and Tobago[^3], and Jamaica[^4] reporting high levels of homicides. 

Saint Lucia, like many of its sister islands, has grappled with the issue of violent crime[^5]. In 2011, after a spate of gang-related homicides, the government implemented an aggressive response under the name, "Operation Restore Confidence." This initiative has since been condemned as unlawful after a number of suspicious homicides committed by police were called into question, with an independent investigation later deeming these to have been extra-judicial.  Seven years on from this incident, Saint Lucia experienced its highest ever homicide count, with 60 persons reportedly killed during the year. 

Using reports sourced from a number of media outlets, I compiled a list of the sixty homicide victims, including demographic information and cause of death. 

# Findings

> "Men are more likely to be victims of homicide"

Consistent with studies in criminology, men were significantly more likely to be victims of homicide than women[^6]. Using 2017 estimates, Saint Lucia had a total population of 178,844, with 51.05% females[^7]. Overall, the country had a per capita homicide rate of 34 per 100,000. If we were to separate the population into two subpopulations by gender and calculate the per capita homicide rate for each subpopulation, the male population would have a per capita murder rate of 62 per 100,000 compared with 6 per 100,000 for the female population.  

![Homicide By Gender](https://nikkevmarshalldotcom.files.wordpress.com/2018/04/homicide-by-gender.jpg)

Despite the lower homicide rate among women, the nature of the homicides is gendered and highlights key local issues pertaining to domestic violence and sexual assault. Each of these homicides involved either intimate partner violence or associated with a sexual assault. 

> "Especially young men"

Young men (less than 35 years old) were particularly vulnerable to homicides, with 35 of the 55 male homicide victims all under the age of 35. This group is the most likely to both perpetrate homicide and other violent crimes and be victims themselves. 

![Male Homicide By Age](https://nikkevmarshalldotcom.files.wordpress.com/2018/04/male-homicide-by-age.jpg)

> "We have a gun problem"

As often reported, guns play a significant role in crime, with 35 of the 60 homicides committed using a gun. This is despite strict gun laws in Saint Lucia regulating the licensing and ownership of firearms[^8]. This highlights the issue of illegal firearms in Saint Lucia, which requires urgent attention. 

![Homicide By Weapon](https://nikkevmarshalldotcom.files.wordpress.com/2018/04/homicide-by-weapon.jpg)

# Conclusions

There are no easy answers to explain the dramatic rise in homicides last year and time may show 2017 to be an anomaly. However, the high prevalence of violence by and against young men, a high risk group given the high unemployment rate among this cohort and other sociocultural factors. The use of illegal firearms is a concern as well, due to their frequent usage in the commission of crimes as a whole and in homicides in particular.  

# Notes

[^1]: http://www.jamaicaobserver.com/news/Extrajudicial-killings-report--disturbing--hopeless-and-questionable---says-former-St-Lucia-PM

[^2]: https://www.insightcrime.org/news/analysis/caribbean-has-violence-problem-not-crime-problem-report/

[^3]: http://www.looptt.com/content/bloody-january-murder-count-60

[^4]: http://jamaica-gleaner.com/article/lead-stories/20180105/2017-murders-divisions-st-james-leads-335-homicides

[^5]: https://www.insightcrime.org/news/analysis/caribbean-has-violence-problem-not-crime-problem-report/

[^6]: https://www.ncbi.nlm.nih.gov/pubmed/1635092

[^7]: http://worldpopulationreview.com/countries/saint-lucia-population/

[^8]: http://www.gunpolicy.org/firearms/region/st-lucia